#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xDBD2CE893E2D1C87 (cfeck@kde.org)
#
Name     : pimcommon
Version  : 18.08.0
Release  : 1
URL      : https://download.kde.org/stable/applications/18.08.0/src/pimcommon-18.08.0.tar.xz
Source0  : https://download.kde.org/stable/applications/18.08.0/src/pimcommon-18.08.0.tar.xz
Source99 : https://download.kde.org/stable/applications/18.08.0/src/pimcommon-18.08.0.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: pimcommon-lib
Requires: pimcommon-license
Requires: pimcommon-locales
BuildRequires : akonadi-contacts-dev
BuildRequires : akonadi-dev
BuildRequires : boost-dev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : grantlee-dev
BuildRequires : kcontacts-dev
BuildRequires : kimap-dev
BuildRequires : kmime-dev
BuildRequires : kpimtextedit-dev
BuildRequires : libkdepim-dev
BuildRequires : qtbase-dev qtbase-extras mesa-dev

%description
No detailed description available

%package dev
Summary: dev components for the pimcommon package.
Group: Development
Requires: pimcommon-lib
Provides: pimcommon-devel

%description dev
dev components for the pimcommon package.


%package lib
Summary: lib components for the pimcommon package.
Group: Libraries
Requires: pimcommon-license

%description lib
lib components for the pimcommon package.


%package license
Summary: license components for the pimcommon package.
Group: Default

%description license
license components for the pimcommon package.


%package locales
Summary: locales components for the pimcommon package.
Group: Default

%description locales
locales components for the pimcommon package.


%prep
%setup -q -n pimcommon-18.08.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1535253621
mkdir clr-build
pushd clr-build
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1535253621
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/pimcommon
cp COPYING %{buildroot}/usr/share/doc/pimcommon/COPYING
cp COPYING.LIB %{buildroot}/usr/share/doc/pimcommon/COPYING.LIB
pushd clr-build
%make_install
popd
%find_lang libpimcommon

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/KF5/PimCommon/AbstractGenericPlugin
/usr/include/KF5/PimCommon/AbstractGenericPluginInterface
/usr/include/KF5/PimCommon/AutoCorrection
/usr/include/KF5/PimCommon/AutoCorrectionLanguage
/usr/include/KF5/PimCommon/AutoCorrectionWidget
/usr/include/KF5/PimCommon/ConfigureImmutableWidgetUtils
/usr/include/KF5/PimCommon/ConfigurePluginDialog
/usr/include/KF5/PimCommon/ConfigurePluginsListWidget
/usr/include/KF5/PimCommon/ConfigurePluginsWidget
/usr/include/KF5/PimCommon/CustomToolsPlugin
/usr/include/KF5/PimCommon/CustomToolsViewInterface
/usr/include/KF5/PimCommon/CustomToolsWidgetng
/usr/include/KF5/PimCommon/CustomTreeView
/usr/include/KF5/PimCommon/GenericGrantleeFormatter
/usr/include/KF5/PimCommon/GenericPlugin
/usr/include/KF5/PimCommon/GenericPluginManager
/usr/include/KF5/PimCommon/KActionMenuChangeCase
/usr/include/KF5/PimCommon/KPimPrintPreviewDialog
/usr/include/KF5/PimCommon/LineEditWithAutoCorrection
/usr/include/KF5/PimCommon/LineEditWithCompleterNg
/usr/include/KF5/PimCommon/LogActivitiesManager
/usr/include/KF5/PimCommon/MetaType
/usr/include/KF5/PimCommon/MigrateApplicationFiles
/usr/include/KF5/PimCommon/MigrateFileInfo
/usr/include/KF5/PimCommon/MinimumComboBox
/usr/include/KF5/PimCommon/NetworkManager
/usr/include/KF5/PimCommon/NetworkUtil
/usr/include/KF5/PimCommon/PimCommonSettings
/usr/include/KF5/PimCommon/PimUtil
/usr/include/KF5/PimCommon/PluginUtil
/usr/include/KF5/PimCommon/RenameFileDialog
/usr/include/KF5/PimCommon/RichTexteditWithAutoCorrection
/usr/include/KF5/PimCommon/ShareServiceUrlManager
/usr/include/KF5/PimCommon/SimpleStringListEditor
/usr/include/KF5/PimCommon/SpellCheckLineEdit
/usr/include/KF5/PimCommon/TemplateListWidget
/usr/include/KF5/PimCommon/TemplateManager
/usr/include/KF5/PimCommon/TranslatorWidget
/usr/include/KF5/PimCommonAkonadi/AnnotationDialog
/usr/include/KF5/PimCommonAkonadi/CheckedCollectionWidget
/usr/include/KF5/PimCommonAkonadi/CollectionAclPage
/usr/include/KF5/PimCommonAkonadi/CollectionAnnotationsAttribute
/usr/include/KF5/PimCommonAkonadi/CollectionTypeUtil
/usr/include/KF5/PimCommonAkonadi/ContentTypeWidget
/usr/include/KF5/PimCommonAkonadi/CreateResource
/usr/include/KF5/PimCommonAkonadi/FetchRecursiveCollectionsJob
/usr/include/KF5/PimCommonAkonadi/GenericPluginInterface
/usr/include/KF5/PimCommonAkonadi/ImapAclAttribute
/usr/include/KF5/PimCommonAkonadi/ImapResourceCapabilitiesManager
/usr/include/KF5/PimCommonAkonadi/IncidencesForWidget
/usr/include/KF5/PimCommonAkonadi/MailUtil
/usr/include/KF5/PimCommonAkonadi/ManageServerSideSubscriptionJob
/usr/include/KF5/PimCommonAkonadi/PluginInterface
/usr/include/KF5/PimCommonAkonadi/SelectMultiCollectionDialog
/usr/include/KF5/pimcommon/abstractgenericplugin.h
/usr/include/KF5/pimcommon/abstractgenericplugininterface.h
/usr/include/KF5/pimcommon/autocorrection.h
/usr/include/KF5/pimcommon/autocorrectionlanguage.h
/usr/include/KF5/pimcommon/autocorrectionwidget.h
/usr/include/KF5/pimcommon/configureimmutablewidgetutils.h
/usr/include/KF5/pimcommon/configureplugindialog.h
/usr/include/KF5/pimcommon/configurepluginslistwidget.h
/usr/include/KF5/pimcommon/configurepluginswidget.h
/usr/include/KF5/pimcommon/customtoolsplugin.h
/usr/include/KF5/pimcommon/customtoolsviewinterface.h
/usr/include/KF5/pimcommon/customtoolswidgetng.h
/usr/include/KF5/pimcommon/customtreeview.h
/usr/include/KF5/pimcommon/genericgrantleeformatter.h
/usr/include/KF5/pimcommon/genericplugin.h
/usr/include/KF5/pimcommon/genericpluginmanager.h
/usr/include/KF5/pimcommon/imapresourcesettings.h
/usr/include/KF5/pimcommon/kactionmenuchangecase.h
/usr/include/KF5/pimcommon/kpimprintpreviewdialog.h
/usr/include/KF5/pimcommon/lineeditwithautocorrection.h
/usr/include/KF5/pimcommon/lineeditwithcompleterng.h
/usr/include/KF5/pimcommon/logactivitiesmanager.h
/usr/include/KF5/pimcommon/metatype.h
/usr/include/KF5/pimcommon/migrateapplicationfiles.h
/usr/include/KF5/pimcommon/migratefileinfo.h
/usr/include/KF5/pimcommon/minimumcombobox.h
/usr/include/KF5/pimcommon/networkmanager.h
/usr/include/KF5/pimcommon/networkutil.h
/usr/include/KF5/pimcommon/pimcommon_debug.h
/usr/include/KF5/pimcommon/pimcommon_export.h
/usr/include/KF5/pimcommon/pimcommonsetting_base.h
/usr/include/KF5/pimcommon/pimcommonsettings.h
/usr/include/KF5/pimcommon/pimutil.h
/usr/include/KF5/pimcommon/pluginutil.h
/usr/include/KF5/pimcommon/renamefiledialog.h
/usr/include/KF5/pimcommon/richtexteditwithautocorrection.h
/usr/include/KF5/pimcommon/shareserviceurlmanager.h
/usr/include/KF5/pimcommon/simplestringlisteditor.h
/usr/include/KF5/pimcommon/spellchecklineedit.h
/usr/include/KF5/pimcommon/templatelistwidget.h
/usr/include/KF5/pimcommon/templatemanager.h
/usr/include/KF5/pimcommon/translatorwidget.h
/usr/include/KF5/pimcommon_version.h
/usr/include/KF5/pimcommonakonadi/annotationdialog.h
/usr/include/KF5/pimcommonakonadi/checkedcollectionwidget.h
/usr/include/KF5/pimcommonakonadi/collectionaclpage.h
/usr/include/KF5/pimcommonakonadi/collectionannotationsattribute.h
/usr/include/KF5/pimcommonakonadi/collectiontypeutil.h
/usr/include/KF5/pimcommonakonadi/contenttypewidget.h
/usr/include/KF5/pimcommonakonadi/createresource.h
/usr/include/KF5/pimcommonakonadi/fetchrecursivecollectionsjob.h
/usr/include/KF5/pimcommonakonadi/genericplugininterface.h
/usr/include/KF5/pimcommonakonadi/imapaclattribute.h
/usr/include/KF5/pimcommonakonadi/imapresourcecapabilitiesmanager.h
/usr/include/KF5/pimcommonakonadi/incidencesforwidget.h
/usr/include/KF5/pimcommonakonadi/mailutil.h
/usr/include/KF5/pimcommonakonadi/manageserversidesubscriptionjob.h
/usr/include/KF5/pimcommonakonadi/pimcommonakonadi_debug.h
/usr/include/KF5/pimcommonakonadi/pimcommonakonadi_export.h
/usr/include/KF5/pimcommonakonadi/plugininterface.h
/usr/include/KF5/pimcommonakonadi/selectmulticollectiondialog.h
/usr/include/KF5/pimcommonakonadi_version.h
/usr/lib64/cmake/KF5PimCommon/KF5PimCommonConfig.cmake
/usr/lib64/cmake/KF5PimCommon/KF5PimCommonConfigVersion.cmake
/usr/lib64/cmake/KF5PimCommon/KF5PimCommonTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KF5PimCommon/KF5PimCommonTargets.cmake
/usr/lib64/cmake/KF5PimCommonAkonadi/KF5PimCommonAkonadiConfig.cmake
/usr/lib64/cmake/KF5PimCommonAkonadi/KF5PimCommonAkonadiConfigVersion.cmake
/usr/lib64/cmake/KF5PimCommonAkonadi/KF5PimCommonAkonadiTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KF5PimCommonAkonadi/KF5PimCommonAkonadiTargets.cmake
/usr/lib64/libKF5PimCommon.so
/usr/lib64/libKF5PimCommonAkonadi.so
/usr/lib64/qt5/mkspecs/modules/qt_PimCommon.pri
/usr/lib64/qt5/mkspecs/modules/qt_PimCommonAkonadi.pri

%files lib
%defattr(-,root,root,-)
/usr/lib64/libKF5PimCommon.so.5
/usr/lib64/libKF5PimCommon.so.5.9.0
/usr/lib64/libKF5PimCommonAkonadi.so.5
/usr/lib64/libKF5PimCommonAkonadi.so.5.9.0
/usr/lib64/qt5/plugins/designer/pimcommonwidgets.so

%files license
%defattr(-,root,root,-)
/usr/share/doc/pimcommon/COPYING
/usr/share/doc/pimcommon/COPYING.LIB

%files locales -f libpimcommon.lang
%defattr(-,root,root,-)

